### ISSUE TITLE
Publish updates to NPM

### ISSUE THREAD

**Issue by jesusprubio** [attekett/Surku#2]
Please, could you republish the package to the NPM registry please? :)

This commit is not published: https://github.com/attekett/Surku/commit/13085e45a9484a5762e7a2deabec2a88e4678bef

**Comment by attekett** [comment]
At least for me "npm install surku" installs version 0.1.10 with "gitHead": "13085e45a9484a5762e7a2deabec2a88e4678bef"

**Comment by jesusprubio** [comment]
Not for me, I've getting this one "58f2d13a07df3479a8e8026edbc6d4ed8fbdd7bb". I've tested (just in case) with node (v0.10.36), node (v0.12.0) and iojs (v1.4.1). In fact the NPM site reflects the last published date as 23 days ago.

https://www.npmjs.com/package/surku

Thanks for the work, I'm really enjoying it :).

**Comment by attekett** [comment]
Really interesting.

I published 0.1.11 and it also shows updated in https://www.npmjs.com/package/surku

Please check that it works for you. :)

**Comment by jesusprubio** [comment]
Working :)

Thank you

**Comment by attekett** [comment]
Nice.

Have fun bug hunting. ;)

**Comment by jesusprubio** [comment]
BTW, just in case :)
- https://gist.github.com/jesusprubio/8f092af4ca252e252eab
- https://github.com/assaultjs/assaultjs
- https://assaultjs.github.io/

We're often in Freenode
